apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  template:
    spec:
      containers:
      - name: todo-backend
        env:
        - name: PORT
          value: "8080"
        - name: MONGO_URI
          value: "mongodb://mongodb.todo-app.svc.cluster.local:27017"
        - name: MONGO_DB_NAME
          value: "todoDB-prod"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
