apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/todo-backend

# Production modifications
patchesStrategicMerge:
- config.yaml

replicas:
- name: todo-backend
  count: 3

images:
  - name: ghcr.io/lakmalniranga/todo-backend
    newTag: v1.0.0
