apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
spec:
  destination:
    namespace: todo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/overlays/prod/mongodb
    repoURL: https://github.com/lakmalniranga/todo-backend-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
