apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: todo-app

resources:
- root-app.yaml
