apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-apps
  namespace: argocd
spec:
  destination:
    namespace: todo-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/apps
    repoURL: https://github.com/lakmalniranga/todo-backend-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true
